---
- name: Get sample models
  git:
    repo: 'https://github.com/tensorflow/serving.git'
    dest: "{{ playbook_dir }}/files/tmp/models"
    version: "{{ tf_serving_tag }}"
  delegate_to: localhost

- name: Download resnet models
  get_url:
    url: http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v1_fp32_savedmodel_NCHW_jpg.tar.gz
    dest: "{{ playbook_dir }}/files/tmp/models/resnet.tar.gz"
    mode: '0755'
  delegate_to: localhost

- name: Get resnet models
  unarchive:
    src: "{{ playbook_dir }}/files/tmp/models/resnet.tar.gz"
    dest: "{{ playbook_dir }}/files/tmp/models/"
  delegate_to: localhost

- name: rename resnet models
  shell: |
    if [ ! -d "{{ playbook_dir }}/files/tmp/models/resnet" ] 
    then 
      mv "{{ playbook_dir }}/files/tmp/models/resnet_v1_fp32_savedmodel_NCHW_jpg" "{{ playbook_dir }}/files/tmp/models/resnet" 
    fi
  delegate_to: localhost
