---
- name: download docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ dockerComposeVersion }}/docker-compose-linux-x86_64 
    dest: files/tmp/docker-compose-{{ dockerComposeVersion }}
  delegate_to: localhost

- name: install docker compose
  copy:
    src: files/tmp/docker-compose-{{ dockerComposeVersion }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
