- name: install virtualenv
  pip:
    name: virtualenv

- name: Create test directory
  file:
    path: /opt/app/test
    state: directory
    mode: '0755'

- name: install tf python lib
  shell: |
    cd /opt/app/test
    virtualenv tfserving_test
    source tfserving_test/bin/activate
    pip install requests tensorflow==1.14 tensorflow-serving-api==1.14
    deactivate
    exit 0
  args:
    executable: /bin/bash
