---
- name: common setup
  hosts: all
  strategy: free
  roles:
  - common

- name: setup tensorflow serving
  hosts: tensorflow_serving
  strategy: free
  tasks:
  - include_role:
      name: "{{ svc_name }}"
    when: "'tensorflow_serving' in group_names"
    loop:
    - caddy
    - envoy
    - tensorflow_serving
    loop_control:
      loop_var: svc_name

- name: setup model_repo
  hosts: model_repo
  strategy: free
  tasks:
  - include_role:
      name: "{{ svc_name }}"
    when: "'model_repo' in group_names"
    loop:
    - caddy
    - envoy
    - model_repo
    loop_control:
      loop_var: svc_name